# Generated by Django 5.2.8 on 2025-11-11 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tower',
            name='difficulty',
            field=models.FloatField(),
        ),
    ]
