# Generated by Django 5.2.8 on 2025-11-12 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_tower_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='tower',
            name='diff_category',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard'), ('difficult', 'Difficult'), ('challenging', 'Challenging'), ('intense', 'Intense'), ('remorseless', 'Remorseless'), ('insane', 'Insane'), ('extreme', 'Extreme'), ('terrifying', 'Terrifying'), ('catastrophic', 'Catastrophic')], default='easy'),
        ),
        migrations.AlterField(
            model_name='tower',
            name='type',
            field=models.CharField(choices=[('tower', 'Tower'), ('mini_tower', 'Mini-Tower'), ('steeple', 'Steeple'), ('citadel', 'Citadel')], default='tower'),
        ),
    ]
