# Generated by Django 5.2.8 on 2025-11-12 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_tower_diff_category_alter_tower_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Creator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='tower',
            name='creators_m2m',
            field=models.ManyToManyField(blank=True, related_name='towers', to='api.creator'),
        ),
    ]
