# Generated by Django 5.2.8 on 2025-11-12 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_creator_tower_creators_m2m'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tower',
            name='creators',
        ),
    ]
