# Generated by Django 5.2.8 on 2025-11-15 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_profile_roblox_user_id_profile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='badge',
            old_name='badge_id',
            new_name='id',
        ),
        migrations.AddField(
            model_name='badge',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
