# Generated by Django 5.2.8 on 2025-11-16 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_badge_id_badge_id_badge_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='area',
            options={},
        ),
        migrations.AddField(
            model_name='area',
            name='required_challenging',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='area',
            name='required_completions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='area',
            name='required_difficult',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='area',
            name='required_hard',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='area',
            name='required_intense',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='area',
            name='required_medium',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='area',
            name='required_remorseless',
            field=models.IntegerField(default=0),
        ),
    ]
