# Generated by Django 5.2.8 on 2025-12-08 00:51

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_area_options_area_required_challenging_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ignored_towers',
            field=models.ManyToManyField(blank=True, related_name='ignored_by', to='api.tower'),
        ),
        migrations.CreateModel(
            name='TowerReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('review_text', models.TextField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.profile')),
                ('tower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tower')),
            ],
            options={
                'unique_together': {('profile', 'tower')},
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='reviewed_towers',
            field=models.ManyToManyField(blank=True, related_name='reviews', through='api.TowerReview', to='api.tower'),
        ),
    ]
