# Generated by Django 5.2.8 on 2025-12-11 00:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_profile_ignored_towers_towerreview_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='complete_towers',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='ignored_towers',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='reviewed_towers',
        ),
        migrations.CreateModel(
            name='ProfileTowerStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('bookmarked', 'Bookmarked'), ('ignored', 'Ignored')], max_length=10)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tower_statuses', to='api.profile')),
                ('tower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_statuses', to='api.tower')),
            ],
            options={
                'unique_together': {('profile', 'tower')},
            },
        ),
    ]
