# Generated by Django 5.2.8 on 2025-12-12 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_profile_complete_towers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creator',
            name='avatar_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='creator',
            name='roblox_user_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
