# Generated by Django 5.2.8 on 2025-12-16 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_creator_avatar_url_creator_roblox_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='towerreview',
            name='summary',
            field=models.TextField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='towerreview',
            name='review_text',
            field=models.TextField(blank=True, max_length=1500, null=True),
        ),
    ]
