# Generated by Django 5.2.8 on 2026-02-03 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_profile_avatar_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiletowerstatus',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
